package io.github.netbeans.mvnrunner;

import java.util.Objects;
import java.util.Properties;
import javax.swing.Action;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TreeExpansionEvent;
import javax.swing.event.TreeExpansionListener;
import javax.swing.table.TableModel;
import javax.swing.tree.TreePath;
import javax.swing.tree.TreeSelectionModel;

import org.netbeans.api.annotations.common.StaticResource;
import org.netbeans.api.settings.ConvertAsProperties;
import org.netbeans.swing.etable.ETable;
import org.netbeans.swing.outline.Outline;
import org.netbeans.swing.outline.TreePathSupport;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.explorer.view.OutlineView;
import org.openide.nodes.AbstractNode;
import org.openide.nodes.Node;
import org.openide.util.ImageUtilities;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;

import lombok.SneakyThrows;

import io.github.netbeans.mvnrunner.node.ProjectNode;
import io.github.netbeans.mvnrunner.node.ProjectRootChildren;
import io.github.netbeans.mvnrunner.util.ActionUtils;
import io.github.netbeans.mvnrunner.util.NodeUtils;
import io.github.netbeans.mvnrunner.util.PropertiesWrapper;

/**
 * The Maven-Runner {@link TopComponent}.
 */
// @formatter:off
@ConvertAsProperties(dtd = "-//io.github.netbeans.mvnrunner//MavenRunnerTopComponent//EN", autostore = false)
@TopComponent.Description(preferredID = "MavenRunnerTopComponent",
        iconBase = "io/github/netbeans/mvnrunner/resources/Maven2IconRun1.png",
        persistenceType = TopComponent.PERSISTENCE_ONLY_OPENED)
@TopComponent.Registration(mode = "properties",
        openAtStartup = true)
@ActionID(category = "Window",
        id = "io.github.netbeans.mvnrunner.MavenRunnerTopComponent")
@ActionReference(path = "Menu/Window", position = 100)
@TopComponent.OpenActionRegistration(displayName = "#CTL_MavenRunnerTopComponentAction",
        preferredID = "MavenRunnerTopComponent")
@Messages({ "CTL_MavenRunnerTopComponentAction=Maven Runner",
        "CTL_MavenRunnerTopComponent=Maven Runner",
        "HINT_MavenRunnerTopComponent=Shows Maven goals as tree",
        "LB_ExpandAll=Expand all",
        "LB_CollapseAll=Collapse all" })
// @formatter:on
public final class MavenRunnerTopComponent extends TopComponent implements ExplorerManager.Provider {

    private static final long serialVersionUID = 1L;

    private JButton runBtn;
    private JButton debugBtn;
    private JButton buildBtn;
    private JButton rebuildBtn;

    public MavenRunnerTopComponent() {
        initComponents();
        setName(Bundle.CTL_MavenRunnerTopComponent());
        setToolTipText(Bundle.HINT_MavenRunnerTopComponent());
        initCustomization();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolbar = new javax.swing.JToolBar();
        scollPane = new OutlineView();

        setLayout(new java.awt.BorderLayout());

        toolbar.setRollover(true);
        add(toolbar, java.awt.BorderLayout.PAGE_START);
        add(scollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scollPane;
    private javax.swing.JToolBar toolbar;
    // End of variables declaration//GEN-END:variables
    private OutlineView treeView;
    private transient Node rootNode;
    private final transient PropertiesWrapper properties = new PropertiesWrapper(new Properties());
    private final transient ExplorerManager explorerManager = new ExplorerManager();

    @Override
    public ExplorerManager getExplorerManager() {
        return explorerManager;
    }

    private static final @StaticResource String EXPAND_ALL_ICON
            = "io/github/netbeans/mvnrunner/resources/tree_expand.png"; // NOI18N
    private static final @StaticResource String COLLAPSE_ALL_ICON
            = "io/github/netbeans/mvnrunner/resources/tree_collapse.png"; // NOI18N
    private static final @StaticResource String REFRESH_ICON = "io/github/netbeans/mvnrunner/resources/refresh.png"; // NOI18N
    private static final @StaticResource String RUN_ICON = "io/github/netbeans/mvnrunner/resources/runProject.png"; // NOI18N
    private static final @StaticResource String DEBUG_ICON = "io/github/netbeans/mvnrunner/resources/debugProject.png"; // NOI18N
    private static final @StaticResource String BUILD_ICON = "io/github/netbeans/mvnrunner/resources/buildProject.png"; // NOI18N
    private static final @StaticResource String REBUILD_ICON
            = "io/github/netbeans/mvnrunner/resources/rebuildProject.png"; // NOI18N

    private void initCustomization() {
        treeView = (OutlineView) this.scollPane;
        Outline outline = treeView.getOutline();
        outline.setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        outline.setTableHeader(null);
        TableModel model = outline.getModel();
        // Receive changed selctions
        model.addTableModelListener(this::handleTableModelChanges);
        associateLookup(ExplorerUtils.createLookup(explorerManager, getActionMap()));
        rootNode = createRootNode();
        invokeInAwtThreadLater(() -> {
            outline.setRootVisible(false);
            explorerManager.setRootContext(rootNode);
            explorerManager.getRootContext().setDisplayName("Maven-Runner-Projects");
        });
        JButton expandAllBtn = new JButton(ImageUtilities.loadImageIcon(EXPAND_ALL_ICON, true));
        expandAllBtn.setToolTipText(Bundle.LB_ExpandAll());
        expandAllBtn.addActionListener(ev -> {
            SwingUtilities.invokeLater(() -> {
                NodeUtils.walkTree(rootNode, treeView::expandNode);
            });
        });
        JButton collapseAllBtn = new JButton(ImageUtilities.loadImageIcon(COLLAPSE_ALL_ICON, true));
        collapseAllBtn.setToolTipText(Bundle.LB_CollapseAll());
        collapseAllBtn.addActionListener(ev -> {
            invokeInAwtThreadLater(() -> {
                NodeUtils.walkTree(rootNode.getChildren(), treeView::collapseNode);
            });
        });
        JButton refreshBtn = new JButton(ImageUtilities.loadImageIcon(REFRESH_ICON, true));
        refreshBtn.setToolTipText("Refresh Tree");
        refreshBtn.addActionListener(ev -> {
            Node n = createRootNode();
            invokeInAwtThreadLater(() -> {
                explorerManager.setRootContext(n);
            });
        });
        runBtn = new JButton(ImageUtilities.loadImageIcon(RUN_ICON, true));
        runBtn.setToolTipText("Run Project");
        runBtn.setEnabled(false);

        debugBtn = new JButton(ImageUtilities.loadImageIcon(DEBUG_ICON, true));
        debugBtn.setToolTipText("Debug Project");
        debugBtn.setEnabled(false);

        buildBtn = new JButton(ImageUtilities.loadImageIcon(BUILD_ICON, true));
        buildBtn.setToolTipText("Build Project");
        buildBtn.setEnabled(false); // build

        rebuildBtn = new JButton(ImageUtilities.loadImageIcon(REBUILD_ICON, true));
        rebuildBtn.setToolTipText("Clean and Build Project");
        rebuildBtn.setEnabled(false); // build

        outline.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> updateBtnState());
        TreePathSupport tps = outline.getOutlineModel().getTreePathSupport();
        tps.addTreeExpansionListener(new TreeExpansionListener() {

            @Override
            public void treeExpanded(TreeExpansionEvent event) {
                TreePath path = event.getPath();
                Object lastPathComponent = path.getLastPathComponent();
                if (lastPathComponent instanceof Node node) {
                    properties.put("expand:" + NodeUtils.getTreePath(node), treeView.isExpanded(node));
                }
            }

            @Override
            public void treeCollapsed(TreeExpansionEvent event) {
                TreePath path = event.getPath();
                Object lastPathComponent = path.getLastPathComponent();
                if (lastPathComponent instanceof Node node) {
                    properties.put("expand:" + NodeUtils.getTreePath(node), treeView.isExpanded(node));
                }
            }
        });

        toolbar.setLayout(new BoxLayout(toolbar, BoxLayout.X_AXIS));
        toolbar.add(refreshBtn);
        toolbar.add(runBtn);
        toolbar.add(debugBtn);
        toolbar.add(Box.createHorizontalStrut(12));
        toolbar.add(buildBtn);
        toolbar.add(rebuildBtn);
        toolbar.add(Box.createHorizontalGlue());
        toolbar.add(expandAllBtn);
        toolbar.add(collapseAllBtn);
    }

    private Node createRootNode() {
        AbstractNode n = new AbstractNode(new ProjectRootChildren(true));
        n.setDisplayName("Projects");
        n.setName("Project-Name");
        return n;
    }

    private void updateBtnState() {
        Outline outline = treeView.getOutline();
        int row = outline.getSelectedRow();
        ETable.RowMapping mapping = new ETable.RowMapping(row, outline.getModel(), outline);
        Node node = (Node) mapping.getTransformedValue(0);
        while (node != null) {
            if ((node instanceof ProjectNode)) {
                ProjectNode pn = (ProjectNode) node;

                runBtn.setEnabled(true);
                Action action = ActionUtils.createProjectRunAction(pn);
                runBtn.setAction(action);
                runBtn.setToolTipText("Run Project (" + pn.getDisplayName() + ")");

                debugBtn.setEnabled(true);
                Action debugAction = ActionUtils.createProjectDebugAction(pn);
                debugBtn.setAction(debugAction);
                debugBtn.setToolTipText("Debug Project (" + pn.getDisplayName() + ")");

                buildBtn.setEnabled(true);
                Action buildAction = ActionUtils.createProjectBuildAction(pn);
                buildBtn.setAction(buildAction);
                buildBtn.setToolTipText("Build Project (" + pn.getDisplayName() + ")");

                rebuildBtn.setEnabled(true);
                Action rebuildAction = ActionUtils.createProjectRebuildAction(pn);
                rebuildBtn.setAction(rebuildAction);
                rebuildBtn.setToolTipText("Clean and Build Project (" + pn.getDisplayName() + ")");
                break;

            }
            node = node.getParentNode();
        }
        if (node == null) {
            runBtn.setAction(null);
            runBtn.setEnabled(false);
        }
        runBtn.updateUI();
    }

    private void handleTableModelChanges(TableModelEvent event) {
        Outline outline = treeView.getOutline();
        if (event.getFirstRow() == TableModelEvent.HEADER_ROW && event.getLastRow() == TableModelEvent.HEADER_ROW) {
            return;
        }
        if (event.getType() != TableModelEvent.INSERT) {
            return;
        }
        int firstRow = Math.max(event.getFirstRow(), 0);
        int lastRow = (event.getLastRow() == TableModelEvent.HEADER_ROW) ? 0 : event.getLastRow();
        for (int i = firstRow; i <= lastRow; i++) {
            ETable.RowMapping mapping = new ETable.RowMapping(i, outline.getModel(), outline);
            Node node = (Node) mapping.getTransformedValue(0);
            if (node == null) {
                continue;
            }
            if (properties.getBoolean("expand:" + NodeUtils.getTreePath(node), false)) {
                invokeInAwtThreadLater(() -> treeView.expandNode(node));
            }
        }
    }

    @SneakyThrows
    private void invokeInAwtThreadAndWait(Runnable runnable) {
        if (SwingUtilities.isEventDispatchThread()) {
            runnable.run();
        } else {
            SwingUtilities.invokeAndWait(runnable);
        }
    }

    private void invokeInAwtThreadLater(Runnable runnable) {
        if (SwingUtilities.isEventDispatchThread()) {
            runnable.run();
        } else {
            SwingUtilities.invokeLater(runnable);
        }
    }

    @SneakyThrows
    @SuppressWarnings("unused")
    void writeProperties(java.util.Properties p) {
        p.putAll(properties.unwrap());
        p.put("version", "2.0");
        NodeUtils.walkTree(rootNode, node -> {
            if (node == null) {
                return;
            }
            invokeInAwtThreadAndWait(() -> {
                p.put("expand:" + NodeUtils.getTreePath(node), Boolean.toString(treeView.isExpanded(node)));
            });
        });
    }

    @SuppressWarnings("unused")
    void readProperties(java.util.Properties p) {
        String pVersion = p.getProperty("version");
        String propVersion = properties.getString("version", "2.0");
        if (!Objects.equals(pVersion, propVersion)) {
            properties.clear();
        }
        properties.putAll(p);
        NodeUtils.walkTree(rootNode, node -> {
            if (properties.getBoolean("expand:" + NodeUtils.getTreePath(node), false)) {
                treeView.expandNode(node);
            }
        });
    }
}
